### ISSUE TITLE
Skisser til prosjekt

### ISSUE THREAD

**Issue by stinawest** [stinawest/how-we-roll#5]

**Comment by Dberg042** [comment]
![main1](https://user-images.githubusercontent.com/62940443/134903518-c35a911d-8350-4812-82cb-572cf1cc61c8.jpeg)

*File Tree

**Comment by Dberg042** [comment]
*  Oppgave Del 1 LHWR01 _Visit Kort Page 

![indexfile](https://user-images.githubusercontent.com/62940443/134903752-56d2e10a-8fae-4489-9974-2524de444818.jpeg)
e_

**Comment by Dberg042** [comment]
* **How We Roll Page** Oppgave 2  LHWR02

![howweroll](https://user-images.githubusercontent.com/62940443/134904052-c2a48502-0dda-4bbb-a094-98a2b5f4dc1c.jpeg)

**Comment by Dberg042** [comment]
* Report Page Oppgave 3 LHWR03

![howweroll](https://user-images.githubusercontent.com/62940443/134904208-e2f0e5e8-2e20-4f49-ba9a-233dc4b3d857.jpeg)

**Comment by Dberg042** [comment]
* Oppgave 4-5 LHWR04 OG LHWR05

![rest av](https://user-images.githubusercontent.com/62940443/134904413-7e7f61c6-f9d0-48a7-8ea5-c3fbd4c61fae.jpeg)

**Comment by Dberg042** [comment]
Jeg kan ta **Oppgave 1** og **java** delen, hvis det passer for dere
